Change Bicep files to conform to new components schema
greenie-msft/container-apps-store-api-microservice pull request #1
Opened 2022-03-16 22:29 UTC by greenie-msft

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2022-03-16 23:13 UTC, ItalyPaleAle requested changes
These are the first things I can see just by looking at the code. But we'd need to test this (once we have a working cluster) before this PR can be merged confidently.

2022-03-16 23:13 UTC, ItalyPaleAle commented on deploy/main.bicep
> +          secretRef: 'masterkey'
The secret definition I believe needs to be moved to the component resource too. I see this still in the app resource

2022-03-16 23:13 UTC, ItalyPaleAle commented on deploy/dapr-component.bicep
> +    version: 'v1'
I believe this needs to be customizable, in case there's something different from v1

2022-03-16 23:13 UTC, ItalyPaleAle commented on deploy/dapr-component.bicep
> +  properties: {
We may need a property to define secrets too

2022-03-17 20:02 UTC, greenie-msft commented on deploy/main.bicep
> +          secretRef: 'masterkey'
Done!

2022-03-17 20:02 UTC, greenie-msft commented on deploy/dapr-component.bicep
> +    version: 'v1'
Done!

2022-03-17 20:02 UTC, greenie-msft commented on deploy/dapr-component.bicep
> +  properties: {
Done!

2022-04-08 16:30 UTC, merged